spring.r2dbc.url=${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/orbitchat}
spring.r2dbc.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.r2dbc.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

spring.flyway.url=${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/orbitchat}
spring.flyway.user=${SPRING_DATASOURCE_USERNAME:postgres}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD:postgres}